made changes according to the feedback
UBC-MDS/Online-Shoppers-Purchasing-Intention-Prediction pull request #131
Opened 2024-12-11 07:55 UTC by jdaduica

I have made changes and updates to the discussion section of our QMD report file. Let me know how it sounds.

2024-12-11 15:58 UTC, Stephanie-Ta requested changes

2024-12-11 15:58 UTC, Stephanie-Ta commented on reports/online_shoppers_purchasing_intention_prediction.qmd
> +The features that are in the dataset are:</br> - The number of account management pages the visitor visited (`Administrative`)</br> - The amount of time in seconds that the visitor spent on account m
The bullet point formatting seems to have changed, and is now condensed into one paragraph. Could you edit this to be bullet points again instead of one paragraph?

2024-12-11 15:58 UTC, Stephanie-Ta commented on reports/online_shoppers_purchasing_intention_prediction.qmd
> +![Distribution of numeric features for each target class.](../results/images/feature_density.png){#fig-feature_density width="85%"}
I'm not sure if the figure sizes should be using quotes or not. The quarto documentation seems to suggest that we don't need quotes. However, if it renders correctly for you, there's no need to change this.

2024-12-11 15:58 UTC, Stephanie-Ta commented on reports/online_shoppers_purchasing_intention_prediction.qmd
> +Determining these important features can help businesses make data-driven improvements to their websites. This can lead to enhancing user engagement, improving the shopping process, and increasing co
Thank you for adding to the discussion!

2024-12-12 05:42 UTC, jdaduica commented on reports/online_shoppers_purchasing_intention_prediction.qmd
> +The features that are in the dataset are:</br> - The number of account management pages the visitor visited (`Administrative`)</br> - The amount of time in seconds that the visitor spent on account m
Hey Stephanie, for this, when you render it the <br> makes the seperate lines, in the source part of the qmd file i try to make it into seperate lines, then save it then reopen it and it goes back to paragraph. I am not sure why but when we render the html its all on seperate lines

2024-12-12 05:43 UTC, Stephanie-Ta commented on reports/online_shoppers_purchasing_intention_prediction.qmd
> +The features that are in the dataset are:</br> - The number of account management pages the visitor visited (`Administrative`)</br> - The amount of time in seconds that the visitor spent on account m
Ahh I see, as long as it renders correctly, then that is ok with me!

2024-12-12 05:48 UTC, waiming commented on reports/online_shoppers_purchasing_intention_prediction.qmd
> +The features that are in the dataset are:</br> - The number of account management pages the visitor visited (`Administrative`)</br> - The amount of time in seconds that the visitor spent on account m
yes the </br> is added by me initially when working on quarto rendering. This is to force the quarto to make it in point form, instead of paragraph.

2024-12-12 06:23 UTC, Stephanie-Ta approved these changes

2024-12-12 06:23 UTC, merged